### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by 18nshinagawa** [18nshinagawa/notes#50] opened 2019-07-09 14:05 UTC
high learning curve makes it difficult for beginners to use this app

though a lot of the controls are seemingly intuitive, they still take a lot of adjusting. personally, i know i still struggle with things like G for graphic, H for hyperlink, J for Java? (code)

so a tutorial would be nice

**Comment by lzhaxi** [comment] 2019-07-15 15:17
Duplicate of #65

**Closed as completed by lzhaxi** 2019-07-15 15:17 UTC
Labels: enhancement, major
